### ISSUE TITLE
pi400kb uses 100% CPU on one core

### ISSUE THREAD

**Issue by Hermann-SW** [Gadgetoid/pi400kb#11]
Could be fixed by adding an usleep() in main processing loop:
https://github.com/Gadgetoid/pi400kb/blob/feature/toggle-hook/pi400.c#L202-L248

**Comment by gpetersson** [comment]
I would recommend using `poll` or `epoll` (or even `select`) instead of a `usleep` since it is designed exactly to solve this problem... it will wait (efficiently) until there is activity on any of the file descriptors you are watching.

**Comment by Gadgetoid** [comment]
@gpetersson agreed- forgot about those! This grew from a very rough gist prototype into a more mature project quite suddenly 🤣

**Comment by normen** [comment]
I made a PR that uses poll(), if only for testing. Seems to work fine for me.
