### ISSUE TITLE
Error on run: usbg_init() no such file or directory.

### ISSUE THREAD

**Issue by ArsenicBismuth** [Gadgetoid/pi400kb#15]
Happens on both mouse connected and disconnected.

The full message I got:

```
Found keyboard at: /dev/hidraw0
Failed to open mouse device
usbg_init()  No such file or directory: couldn't init gadget state
 
Error on usbg init
Error: USBG_ERROR_NOT_FOUND : Not found (file or directory removed)
```

**Comment by ArsenicBismuth** [comment]
Missed the step to run this:

`sudo modprobe libcomposite`

So, it seems like it needs to be done every time. The positioning on the instruction made me confusing it for one-time step.

**Comment by Gadgetoid** [comment]
Hmmm, pi400kb is supposed to do this for you!

https://github.com/Gadgetoid/pi400kb/blob/85aa4027cfd507ccd6f69a637b14183bb4970a56/pi400.c#L39-L51

You can also add it to modules_load or /etc/modules
