### ISSUE TITLE
Thanks, I can now type with pi 400 on my Ipad while ssh/vnc-ing to it

### ISSUE THREAD

**Issue by ahasani** [Gadgetoid/pi400kb#17]
Hi @Gadgetoid, really appreciate you made this, you pointed me to learning about libusbgx. I added ECM so that i could ssh/vnc to the PI 400 so that it's not just a "dumb" keyboard while not relying on known WIFI either.
With ipad pro it's wickedly nifty and geeky ;)

Having portable access to full linux and arm with GPIO while also act as portable keyboard for Ipad.....priceless

Cheers

**Comment by Gadgetoid** [comment]
Ooooh I never imagined it could work with an iPad Pro as a sort of... real/virtual machine! That's awesome.
