### ISSUE TITLE
how to i connect it with windows ?

### ISSUE THREAD

**Issue by Prisoner2-6-7** [Gadgetoid/pi400kb#31]
Sorry if i am not seeing this but i cant find in your repo on how to connect it with windows pc's or even with linux

**Comment by Gadgetoid** [comment]
Same way you connect any other keyboard. With a USB cable...

**Comment by Prisoner2-6-7** [comment]
> Same way you connect any other keyboard. With a USB cable...

Sorry but  I think I am kind of confused let me tell you what I understand I want to use my raspberry pi keyboard and mouse as a hid device for another PC so I install the repo into my raspberry pi and connect my mouse and keyboard to the Pi but how to I control my PC with the mouse and keyboard of the pi.

**Comment by Gadgetoid** [comment]
This only works with the Pi 400, it doesn't make any effort to detect/use other keyboards and that's outside the scope of the project.

I think the Pi 4 has USB OTG on the Type-C port, unless I'm imagining it, so it's probably possible to do what you want (going by your previous edit) but I think you're probably looking for a software KVM like Barrier and not this project- https://github.com/debauchee/barrier/releases
