### ISSUE TITLE
sudo: unable to execute ./pi400kb: No such file or directory

### ISSUE THREAD

**Issue by TanishiWalter** [Gadgetoid/pi400kb#38]
When trying to run the script, error mentioned above appears, I did follow every step in Quickstart, but I am not sure if I did the add to config.txt right, because there are multiple files like that in /boot/

**Comment by TiranexDev** [comment]
i have the same issue but i have 64 bit system

**Comment by HarvsG** [comment]
I had the same issue on 64bit Ubuntu desktop. I will try and compile myself

**Comment by SnowyJaguar1034** [comment]
> I had the same issue on 64bit Ubuntu desktop. I will try and compile myself

Did this work for you?
